// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFQMXtNw7p8C8CfHyobm2f_O8pRxpDzTo',
    appId: '1:819699009606:android:ef15c6bc88155657e2a247',
    messagingSenderId: '819699009606',
    projectId: 'sigopal',
    storageBucket: 'sigopal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATYBfQfuPbPadkk8c2_4NYjp4c4pdiSqA',
    appId: '1:706968067138:ios:a3760bd5600f2b2e76e1db',
    messagingSenderId: '706968067138',
    projectId: 'myflutter-new-project',
    storageBucket: 'myflutter-new-project.appspot.com',
    iosClientId: '706968067138-j6qui6ps98er4ufvj0km1ubv01uppgra.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUilogin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVILo9spzZGrAQeLQZyEnxcjh4Cpt9Ffw',
    appId: '1:819699009606:web:b9db3bbc5c8a8894e2a247',
    messagingSenderId: '819699009606',
    projectId: 'sigopal',
    authDomain: 'sigopal.firebaseapp.com',
    storageBucket: 'sigopal.firebasestorage.app',
    measurementId: 'G-FYK49BM325',
  );

}